homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'


urlpatterns = [
    path('blog/', views.BlogView.as_view() , name='blog'),
    path('post/<int:pk>/', views.PostView.as_view(), name='detail_post'),
    path('add_post/', views.AddPostView.as_view(), name='add_post'),
    path('post/edit/<int:pk>/', views.UpdatePostView.as_view(), name='edit_post'),
    path('post/delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<str:category>', views.category_page, name='category_page'),
    path('like/<int:pk>', views.LikeView, name='like_post'),

    
    path('', views.index, name='index'),
    path('skills/', views.skills, name='skills'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('form/', views.form, name='form'),
    path('show-form/', views.showform, name='showform'),
    path('delete-activity/<int:pk>/', views.delete_activity, name='delete_activity'),
   

]

members/urls.py
from django.urls import path
from .views import UserRegView



urlpatterns = [
    path('register/', UserRegView.as_view(),name='register'),

]

personal_website/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls'), namespace='homepage')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime,date

# Create your models here.

class ScheduleModel(models.Model):
    date = models.DateField()
    time = models.TimeField(auto_now_add=False)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=50)

    def __str__(self):
        return "{}.{}".format(self.id, self.name)

class CategoryManager(models.Manager):
    def create_cate(self, name):
        cat = self.create(name=name)
        # do something with the book
        return cat

class Category(models.Model):
    name = models.CharField(max_length=250)
    objects = CategoryManager()
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('homepage:blog')
    
# cat1 = Category.objects.create_cate("HIIHIH Science")
# cat1.save()
# print("hi")
# print(Category.objects.all().count())

class BlogModel(models.Model):
    title = models.CharField(max_length=250, default="Title")
    title_tag = models.CharField(max_length=100)
    category = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    body = models.TextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    snippet = models.CharField(max_length=150)
    likes = models.ManyToManyField(User, related_name = 'blog_posts')
    
    def total_likes(self):
        return self.likes.count()
    def __str__(self):
        return self.title+ " | " + str(self.author)

    def get_absolute_url(self):
        return reverse('homepage:detail_post', kwargs={'pk': self.pk})

homepage/forms.py
from django import forms
from .models import ScheduleModel, BlogModel, Category
import datetime

cats = Category.objects.all().values_list('name','name')

class ScheduleForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Project's Title",}))
    category = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Project's Category",}))
    date = forms.DateField(input_formats=['%Y-%m-%d'], initial=datetime.date.today(), widget=forms.TextInput(attrs={'class': 'form-control'}))
    time = forms.TimeField(input_formats=['%H:%M:%S'], initial=datetime.time, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = ScheduleModel
        fields = ['date','time','name','category',]


class BlogForm(forms.ModelForm):
    class Meta:
        model= BlogModel
        fields = ('title','title_tag','category','author','image','body','snippet')
        widgets = {
            'title': forms.TextInput(attrs={'class=':'form-control'}),
            'title_tag': forms.TextInput(attrs={'class=':'form-control'}),
            'category': forms.Select(choices=cats,attrs={'class=':'form-control'}),
            'author': forms.Select(attrs={'class=':'form-control'}),
            'body': forms.TextInput(attrs={'class=':'form-control'}),
            'snippet': forms.Textarea(attrs={'class=':'form-control'}),
        }

homepage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.core.mail import send_mail
from .forms import ScheduleForm, BlogForm

from .models import ScheduleModel, BlogModel, Category
from django.contrib import messages

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect


class BlogView(ListView):
    model = BlogModel
    template_name = '3_blog.html'
    ordering = ['-post_date']
    cat_menu = Category.objects.all()
 

    # def get_context_data(self,*args,**kwargs):
    #     cat_menu = Category.objects.all()
    #     print(cat_menu)
    #     context = super(BlogView,self).get_context_data(*args,**kwargs)
    #     context['cat_menu'] = cat_menu
    #     return context

class PostView(DetailView):
    model = BlogModel
    template_name = '3b_blog-post.html'

    def get_context_data(self,*args, **kwargs):
        context = super(PostView,self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(BlogModel, id = self.kwargs['pk'])
        total_likes = stuff.total_likes()

        liked = False
        if stuff.likes.filter(id = self.request.user.id ).exists():
            liked = True

        context['total_likes'] = total_likes
        context['liked'] = liked
        return context

class AddPostView(CreateView):
    model = BlogModel
    form_class = BlogForm
    template_name = '3c_add_post.html'

    # fields = '__all__'

class UpdatePostView(UpdateView):
    model = BlogModel
    form_class = BlogForm
    template_name = '3d_update_post.html'
    # fields = ['title','title_tag','body']

class DeletePostView(DeleteView):
    model = BlogModel
    template_name = '3e_delete.html'
    success_url = reverse_lazy('homepage:blog')
    
class AddCategoryView(CreateView):
    model = Category
    template_name = '3f_add_cat.html'
    fields = '__all__'
  

def category_page(request, category):
    cat = category.replace('-',' ')
    data = BlogModel.objects.filter(category = cat)
    return render(request,'3g_category_page.html', {'title':cat, 'data':data})

def LikeView(request,pk):
    post = get_object_or_404(BlogModel, id= request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('homepage:detail_post', args=[str(pk)]))

# Function Based View
def blog(request):
    BlogModel.objects.all().remove()
    if request.method == 'GET':
        posts = BlogModel.objects.all()
        print(posts)
        print("AA")
        return render(request, '3_blog.html', {'posts':posts})
   
def post(request,pk):
    posting = get_object_or_404(BlogModel, pk=pk)
    return render(request, '3b_blog-post.html', {'posting':posting})

def index(request):
    return render(request, '1_home.html' )

def skills(request):
    return render(request, '2_skills.html' )

def blog(request):
    return render(request, '3_blog.html' )

def contact(request):
    if request.method == 'POST':
        mail = request.POST['mail']
        title = request.POST['title']
        message = request.POST['message']
        whole_message = "Email:"+  mail + "\ntitle: " + title + "\nmessage:" + message
        send_mail('['+mail+ ' sent you a message]',
        whole_message,
        settings.EMAIL_HOST_USER,
        ['fathinahai@gmail.com'],
        fail_silently = False)
        context = {'display':'<h3>Your message is sent! I will reach out to you shortly</h3>'}
        return render(request, '4_contact.html',context)
    return render(request, '4_contact.html')


def showform(request):
    data = ScheduleModel.objects.all()
    return render(request, '6_showform.html', {'data': data})

def delete_activity(request, pk):
    activity = get_object_or_404(ScheduleModel, pk=pk)
    activity.delete()

    return redirect('homepage:showform')

def form(request):
    if request.method == "POST":
        data = ScheduleForm(request.POST)
        if data.is_valid():
            data.save()
            return redirect('homepage:showform')
        else:
            messages.warning(request, 'Data input is not valid, Please try again!')
    else:
        data = ScheduleForm()

    return render(request, '5_form.html', {'form': data})
    


    

homepage/templates/0_base.html
{% load categories %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
	    <title>{% block title %} Fathinah Izzati {% endblock %}</title>
		{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">{% endblock %}
		<script type="text/javascript" src='https://cdn.tiny.cloud/1/bqjttcmm95v7zb9ztqk44v8ewn4ddb3zt6tns3cr19lag8bp/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
		{% block js %}
		{% endblock %}
		
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light nav-color navbar-right">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse right" id="navbarNav">
		    <ul class="navbar-nav ">
		      <li class="nav-item active">
		        <a class="nav-link" href="{% url 'homepage:index' %}">HOME </a>
		      </li>
		      <!--sr only gue apus diatas-->
			  
			  <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="{% url 'homepage:blog' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				  BLOG
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{% url 'homepage:blog' %}">All Blogs</a>
				  	{% if user.is_authenticated %}
						<a class="dropdown-item" href="{% url 'homepage:add_post' %}">Add New Post</a>
						<a class="dropdown-item" href="{% url 'homepage:add_category' %}">Add New Category</a>
					{% endif %}
					<div class="dropdown-divider"></div>
					{% get_categories %}
				</div>
			  </li>
			  
			  {% if user.is_authenticated %}
			  <li class="nav-item">
		        <a class="nav-link" href="{% url 'logout' %}">LOG OUT</a>
		      </li>
			  {% else %}
			  <li class="nav-item">
		        <a class="nav-link" href="{% url 'register' %}">REGISTER</a>
			  </li>
			  <li class="nav-item">
		        <a class="nav-link" href="{% url 'login' %}">LOG IN</a>
			  </li>

			  {% endif %}


		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'homepage:contact' %}">CONTACT</a>
		      </li>
                <li class="nav-item">
		        <a class="nav-link" href="{% url 'homepage:form' %}">FORM</a>
		      </li>
                <li class="nav-item">
		        <a class="nav-link" href="{% url 'homepage:showform' %}">SHOW FORM</a>
		      </li>

		    </ul>
		  </div>
		</nav>
		
		{% block content %}

		{% endblock %}

		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</body>
</html>

homepage/templates/1_home.html
{% extends '0_base.html' %}
{% load static %}
{% block content %}

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>
				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div id="main">
				 <h1>HI, I’M THINA</h1>
				 <hr>
				 <p>I’m a second year student majoring in Computer Science</p>
			</div>
		</div>
		
			
		
{% endblock %}

homepage/templates/2_skills.html
{% extends '0_base.html' %}
{% load static %}
{% block content %}

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>

				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div id="main">
				 <img class="circle" src="{% static 'images/pena-bulat.png' %}">
				 <h3 class="desc">WRITING & BLOGGING</h3>
			</div>
		</div>
		
			
		
{% endblock %}

homepage/templates/3_blog.html
{% extends '0_base.html' %}
{% load static %}


{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}
{% block content %}
  <main role="main">
		
	<div class="album py-5">
	  <div class="container">
		
		{% if user.is_authenticated %}
		<button type="button" class="btn btn-secondary btn-lg btn-block my-3 btn-light"><a href="{% url 'homepage:add_post' %}">Add New Post</a></button>
		<button type="button" class="btn btn-secondary btn-lg btn-block my-3 btn-light"><a href="{% url 'homepage:add_category' %}">Add New Category</a></button>
		<p>Welcome {{ user.username }}</p>
		
		{% endif %}
		
		<div class="row">	
		{% for post in object_list %}
		  <div class="col-md-4">
			<div class="mb-4 box-shadow">
			{% if post.image %}
			  <img class="card-img-top" src="{{ post.image.url }}">
			{% endif %}
			  <div class="card-body">
				<h6>{{post.title}}</h6>
				<small><a href="{% url 'homepage:category_page' post.category|slugify %}">{{post.category}}</a></small>
				<p class="card-text">{{ post.snippet }}</p>
				<div class="d-flex justify-content-between align-items-center">
				  <div class="btn-group">
					<button type="button" class="btn btn-sm"><a href="{% url 'homepage:detail_post' post.pk %}">View</a></button>
					{% if user.is_authenticated %}
					<button type="button" class="btn btn-sm"><a href="{% url 'homepage:edit_post' post.pk %}">Edit</a></button>
					<button type="button" class="btn btn-sm"><a href="{% url 'homepage:delete_post' post.pk %}">Delete</a></button>
					{% endif %}
					</div>
				  <small>{{ post.post_date }}</small>
				</div>
			  </div>
			</div>
		  </div>

		{%endfor%}
		</div>
	  </div>
	</div>
  </main>
{% endblock %}

homepage/templates/3b_blog-post.html
{% extends '0_base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}
{% block content %}

		<div class = "container">
			<div id="main">
				<h3>{{ object.title }}</h3>
				<p>{{ object.post_date }}</p>
				<p>{{ object.body|safe }}</p>
				<small>{{ object.author.first_name }}</small> 
				{% if user.is_authenticated %}
				<a href="{% url 'homepage:edit_post' object.pk %}"><br><small>(Edit)</small></a>
				<br>
				<a href="{% url 'homepage:delete_post' object.pk %}"><small>(Delete)</small></a>
				{% endif %}
				<p>{{ total_likes }} Likes</p>
				<form action="{% url 'homepage:like_post' object.pk %}" method="POST">
					{% csrf_token %}
					{% if liked %}
					<button type="submit" name="post_id" class="btn btn-danger btn-sm" value="{{ object.id }}">Unike</button>
					{% else %}
						<button type="submit" name="post_id" class="btn btn-sm" value="{{ object.id }}">Like</button>
					{% endif %}
					</form>
			</div>
		</div>
		
{% endblock %}

homepage/templates/3c_add_post.html
{% extends '0_base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}
{% block title %} Create a Post {% endblock %}
{% block js %}
<script type="text/javascript">
    tinymce.init({
        selector:  '#id_body',
        width: 600,
        height: 300,
        plugins: [
        'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
        'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
        'table emoticons template paste help'
        ],
        toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
        'bullist numlist outdent indent | link image | print preview media fullpage | ' +
        'forecolor backcolor emoticons | help',
        menu: {
        favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | spellchecker | emoticons'}
        },
        menubar: 'favs file edit view insert format tools table help',
        content_css: 'css/content.css'
    });
</script>
{% endblock %}

{% block content %}
		<div class = "container">
            {% if user.is_authenticated %}
            <h1>Create a Post</h1>
            <div class="form-group">
				<form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <button class="btn btn-secondary">Post</button>
                </form>
            </div>
            {% else %}
            <h3>You're not allowed here.</h3>
            {% endif %}	
        </div>
        <!-- <script>
            var name = "{{ user }}";
            document.getElementById("person").value
            = name;

        </script> -->
{% endblock %}

homepage/templates/3d_update_post.html
{% extends '0_base.html' %}
{% load static %}

{% block title %} Edit a Post {% endblock %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}

{% block js %}
<script type="text/javascript">
    tinymce.init({
        selector:  '#id_body',
        width: 600,
        height: 300,
        plugins: [
        'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
        'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
        'table emoticons template paste help'
        ],
        toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
        'bullist numlist outdent indent | link image | print preview media fullpage | ' +
        'forecolor backcolor emoticons | help',
        menu: {
        favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | spellchecker | emoticons'}
        },
        menubar: 'favs file edit view insert format tools table help',
        content_css: 'css/content.css'
    });
</script>
{% endblock %}

{% block content %}
<div class = "container">
    {% if user.is_authenticated %}
    <h1>Edit a Post</h1>
    <div class="form-group">
        <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Post</button>
        </form>
    </div>
    {% else %}
    <h3>You're not allowed here.</h3>
    {% endif %}	
</div>

{% endblock %}

homepage/templates/3e_delete.html
{% extends '0_base.html' %}
{% load static %}

{% block title %} Edit a Post {% endblock %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}
{% block content %}
		<div class = "container">
            {% if user.is_authenticated %}
            <h1>Delete a Post</h1>
            <div class="form-group">
				<form method="POST">
                {% csrf_token %}
                 <p>You sure?</p>
                <button class="btn btn-secondary">Yes</button>
                </form>
            </div>
            {% else %}
            <h3>You're not allowed here.</h3>
            {% endif %}	
		</div>

			
		
{% endblock %}

homepage/templates/3f_add_cat.html
{% extends '0_base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}
{% block title %} Create a Post {% endblock %}

{% block content %}
		<div class = "container">
            {% if user.is_authenticated %}
            <h1>Create a Category</h1>
            <div class="form-group">
				<form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-secondary">Post</button>
                </form>
            </div>
            {% else %}
            <h3>You're not allowed here.</h3>
            {% endif %}	
        </div>
{% endblock %}

homepage/templates/3g_category_page.html
{% extends '0_base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_blog.css' %}">{% endblock %}
{% block content %}
  <main role="main">
	<div class="album py-5">
	  <div class="container">
        {% if data %}
        <h3 class="py-2"> {{ title }} </h3>
		<div class="row">	
            {% for post in data %}
            <div class="col-md-4">
                <div class="mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                <div class="card-body">
                    <h6>{{post.title}}</h6>
                    <p class="card-text">{{post.body|slice:":200"|striptags}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm"><a href="{% url 'homepage:detail_post' post.pk %}">View</a></button>
                        {% if user.is_authenticated %}
                        <button type="button" class="btn btn-sm"><a href="{% url 'homepage:edit_post' post.pk %}">Edit</a></button>
                        <button type="button" class="btn btn-sm"><a href="{% url 'homepage:delete_post' post.pk %}">Delete</a></button>
                        {% endif %}
                    </div>
                    <small>{{ post.post_date }}</small>
                    </div>
                </div>
                </div>
            </div>
            {%endfor%}
        </div>
        {% else %}
            
        {% endif %}
	  </div>
	</div>
  </main>
{% endblock %}

homepage/templates/4_contact.html
{% extends '0_base.html' %}
{% load static %}
{% block content %}
			<div id="socmed">
				<a href="https://instagram.com/fathinasma/"><img src="{% static 'images/ig.png' %}"></a>
				<a href="https://github.com/fathinah"><img src="{% static 'images/github.png' %}"></a>
				<a href="https://medium.com/@fathinah"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<form method="post" action="{% url 'homepage:contact' %}" name="message">
			{% csrf_token %}
			<input type="text" name="mail" placeholder="Email"><br>
			<input type="text" name="title" placeholder="Title"><br>
			<textarea name="message" placeholder="Message..."></textarea>
			<input onclick="myFunction()" type="submit" value="Submit">
			<input type="reset" value="Reset">

			{{display|safe}}
			</form>
{% endblock %}

homepage/templates/5_form.html
{% extends '0_base.html' %}
{% load static %}
{% block content %}
        <h3>Add a reminder</h3>

        <form action="{% url 'homepage:form' %}" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            {% with url_name=request.resolver_match.url_name %}
                <button class="btn-success" type="submit">Add</button>
                </form>

            {% endwith %}

{% endblock %}

homepage/templates/6_showform.html
{% extends '0_base.html' %}
{% load static %}
{% block content %}

    <div style="text-align: center">
        <h3>Fathinah's Schedule</h3>
        <table class="table">
            <thead>
            <tr>
                <th> No </th>
                <th>Activity</th>
                <th>Category</th>
                <!-- <th>Day</th> -->
                <th>Date</th>
                <th>Time</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                {% for i in data %}
                    <tr>
                        <th>{{ forloop.counter}}</th>
                        <td>{{ i.name }}</td>
                        <td>{{ i.category }}</td>
                        <td>{{ i.date }}</td>
                        <td>{{ i.time }}</td>

                        <td><a href="{% url 'homepage:delete_activity' i.pk %}">
                            <button class="btn btn-primary"> Delete</button>
                        </a></td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

homepage/templates/all_categories.html
{% for cat in categories %}
    <a  class="dropdown-item" href="{% url 'homepage:category_page' cat.name|slugify %}">{{ cat.name }}</a>
{% endfor %}